### ISSUE TITLE
Quartz64 model B not booting

### ISSUE THREAD

**Issue by phodina** [manjaro-arm/quartz64-bsp-images#2]
Hi,

I've downloaded the firmware image, verified the checksum and wrote the image to the disk. Checked in fdisk and saw 3 partitions.

However, once I plugged the microSD card into the slot and powered up the quartz64 model B board I firstly got white led which after few seconds turned into red led flashing.

Could you please help me boot the image?

**Comment by zamadatix** [comment]
A few notes for other lost travelers from my first boot experience today:

- If you do not have a battery you need to jumper the "ON/OFF_BATT" for boot to be reliable.
- The white LED near the power/reset buttons should turn on during early boot
- The red LED near the power/reset buttons should double blink continuously in a successful boot
- The device will DHCP without a hostname and locally administered (aka "private" or "non assigned") MAC address
- SSH with root@ip will get you to an initial setup screen where you configure usernames/passwords/hostnames

It might be worth putting some of the above info in the README.md

**Comment by Strit** [comment]
> It might be worth putting some of the above info in the README.md.

The only reason it's needed to do this via SSH at this point, is that Display Out is not working at all yet.
Once that works, you can do it with a keyboard connected to the device.

**Comment by zamadatix** [comment]
Sure but that may still be many months by the looks of the VOP project state and it is still useful information to many even after video output is working,

**Comment by snblackout** [comment]
Thanks for the brief instructions @zamadatix .  It helped me and was able to ssh in.

Any idea on estimate for a fully functional desktop environment for this device?

**Comment by Strit** [comment]
> Any idea on estimate for a fully functional desktop environment for this device?

As soon as it has working video out, we will start providing the other editions for it.

**Comment by snblackout** [comment]
> As soon as it has working video out, we will start providing the other editions for it.

OK.  I'm afraid to ask about any estimate on video out.

I'm here for any public testing of anything.  Motivated to test to get this working.  My primary purpose for the Quartz64 will be video output, so any help in that area to move things along benefits me.

**Comment by Strit** [comment]
I have no estimate.

But you can follow along on Matrix #quartz64:matrix.org or it's bridged Discard and IRC channels.
